### ISSUE TITLE
2.1 create calibration paradigm

### ISSUE THREAD

**Issue by Erfansalehii** [VinayIN/Myendtris#8]

**Comment by VinayIN** [comment]
- Abhishek (Researching)
- Viswa ( Coding)
- Kalyani ( Coding)
- Erfan ( )
- Akhila ( Documentation)
-  Kumaraguru (Coding)

**Comment by VinayIN** [comment]
As per this, I am adding @KalyniMenon  and @Mulla-26  to the PR: https://github.com/VinayIN/Myendtris/pull/12
